# Generated by Django 4.2.2 on 2023-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Mendator', 'Mendator')], default='User', max_length=10),
        ),
    ]
