# Generated by Django 4.2.2 on 2023-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_enable_alter_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
