# Generated by Django 4.2.2 on 2023-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='token',
            new_name='accessToken',
        ),
        migrations.AddField(
            model_name='customer',
            name='refreshToken',
            field=models.CharField(default='', max_length=500),
        ),
    ]
